[profile.dev]
opt-level = 2

[profile.release]
opt-level = 2

[package]
name = "wasm_script"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]