[package]
name = "wasmtester"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utf16_lit = "2.0.2"
lazy_static = "1.4.0"

[dependencies.strace_core]
path = "../StraceCore"